urlK = "url"
nameK = "name"
brandK = "brand"
priceK = "price"
descriptionK = "description"
feedbackK = "feedback"
travelDistanceK = "travelDistance"
bottomOutK = "bottomOut"
actuationK = "actuation"
purchaseQuantityK = "purchaseQuantity"
variantIndicatorK = "variantIndicator"

variantIdK = "variantId"
storeNameK = "storeName"
vendorsK = "vendors"
variantsK = "variants"
